spring.application.name=VitAl
server.port=30992
# db source url
spring.datasource.url=${DB_URL}

# db response name
spring.datasource.username=root

# db response password
spring.datasource.password=${DB_PASSWORD}

# Mail Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

#???? sql ???
spring.jpa.properties.hibernate.show_sql=true
#sql ??? ?? ???
spring.jpa.properties.hibernate.format_sql=true
#db ??? ??. ?? ??? ?? ? ??
spring.jpa.hibernate.ddl-auto=update

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

# Gemini API Configuration
gemini.model=gemini-2.0-flash-exp
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash-exp:generateContent
gemini.api.key=${GEMINI_API_KEY}

# Application Defaults
app.defaults.age=25
gemini.temperature=0.7
gemini.max-tokens=2000
logging.level.org.springframework.web=DEBUG
spring.profiles.include=jwt
spring.profiles.active=prod

spring.jackson.serialization.FAIL_ON_EMPTY_BEANS=false

# Swagger Configuration
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.operations-sorter=method
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.disable-swagger-default-url=true


